// pages/icon/icon.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    fontclass: [
      { fontname: 'check-circle' },
      { fontname: 'CI' },
      { fontname: 'Dollar' },
      { fontname: 'compass' },
      { fontname: 'close-circle' },
      { fontname: 'frown' },
      { fontname: 'info-circle' },
      { fontname: 'left-circle' },
      { fontname: 'down-circle' },
      { fontname: 'EURO' },
      { fontname: 'copyright' },
      { fontname: 'minus-circle' },
      { fontname: 'meh' },
      { fontname: 'plus-circle' },
      { fontname: 'play-circle' },
      { fontname: 'question-circle' },
      { fontname: 'Pound' },
      { fontname: 'right-circle' },
      { fontname: 'smile' },
      { fontname: 'trademark' },
      { fontname: 'time-circle' },
      { fontname: 'timeout' },
      { fontname: 'earth' },
      { fontname: 'YUAN' },
      { fontname: 'up-circle' },
      { fontname: 'warning-circle' },
      { fontname: 'sync' },
      { fontname: 'transaction' },
      { fontname: 'undo' },
      { fontname: 'redo' },
      { fontname: 'reload' },
      { fontname: 'reloadtime' },
      { fontname: 'message' },
      { fontname: 'dashboard' },
      { fontname: 'issuesclose' },
      { fontname: 'poweroff' },
      { fontname: 'logout' },
      { fontname: 'piechart' },
      { fontname: 'setting' },
      { fontname: 'eye' },
      { fontname: 'location' },
      { fontname: 'edit-square' },
      { fontname: 'export' },
      { fontname: 'save' },
      { fontname: 'Import' },
      { fontname: 'appstore' },
      { fontname: 'close-square' },
      { fontname: 'down-square' },
      { fontname: 'layout' },
      { fontname: 'left-square' },
      { fontname: 'play-square' },
      { fontname: 'control' },
      { fontname: 'codelibrary' },
      { fontname: 'detail' },
      { fontname: 'minus-square' },
      { fontname: 'plus-square' },
      { fontname: 'right-square' },
      { fontname: 'project' },
      { fontname: 'wallet' },
      { fontname: 'up-square' },
      { fontname: 'calculator' },
      { fontname: 'interation' },
      { fontname: 'check-square' },
      { fontname: 'border' },
      { fontname: 'border-outer' },
      { fontname: 'border-top' },
      { fontname: 'border-bottom' },
      { fontname: 'border-left' },
      { fontname: 'border-right' },
      { fontname: 'border-inner' },
      { fontname: 'border-verticle' },
      { fontname: 'border-horizontal' },
      { fontname: 'radius-bottomleft' },
      { fontname: 'radius-bottomright' },
      { fontname: 'radius-upleft' },
      { fontname: 'radius-upright' },
      { fontname: 'radius-setting' },
      { fontname: 'adduser' },
      { fontname: 'deleteteam' },
      { fontname: 'deleteuser' },
      { fontname: 'addteam' },
      { fontname: 'user' },
      { fontname: 'team' },
      { fontname: 'areachart' },
      { fontname: 'linechart' },
      { fontname: 'barchart' },
      { fontname: 'pointmap' },
      { fontname: 'container' },
      { fontname: 'database' },
      { fontname: 'sever' },
      { fontname: 'mobile' },
      { fontname: 'tablet' },
      { fontname: 'redenvelope' },
      { fontname: 'book' },
      { fontname: 'filedone' },
      { fontname: 'reconciliation' },
      { fontname: 'file-exception' },
      { fontname: 'filesync' },
      { fontname: 'filesearch' },
      { fontname: 'solution' },
      { fontname: 'fileprotect' },
      { fontname: 'file-add' },
      { fontname: 'file-excel' },
      { fontname: 'file-exclamation' },
      { fontname: 'file-pdf' },
      { fontname: 'file-image' },
      { fontname: 'file-markdown' },
      { fontname: 'file-unknown' },
      { fontname: 'file-ppt' },
      { fontname: 'file-word' },
      { fontname: 'file' },
      { fontname: 'file-zip' },
      { fontname: 'file-text' },
      { fontname: 'file-copy' },
      { fontname: 'snippets' },
      { fontname: 'audit' },
      { fontname: 'diff' },
      { fontname: 'Batchfolding' },
      { fontname: 'securityscan' },
      { fontname: 'propertysafety' },
      { fontname: 'safetycertificate' },
      { fontname: 'insurance' },
      { fontname: 'alert' },
      { fontname: 'delete' },
      { fontname: 'hourglass' },
      { fontname: 'bulb' },
      { fontname: 'experiment' },
      { fontname: 'bell' },
      { fontname: 'trophy' },
      { fontname: 'rest' },
      { fontname: 'USB' },
      { fontname: 'skin' },
      { fontname: 'home' },
      { fontname: 'bank' },
      { fontname: 'filter' },
      { fontname: 'funnelplot' },
      { fontname: 'like' },
      { fontname: 'unlike' },
      { fontname: 'unlock' },
      { fontname: 'lock' },
      { fontname: 'customerservice' },
      { fontname: 'flag' },
      { fontname: 'moneycollect' },
      { fontname: 'medicinebox' },
      { fontname: 'shop' },
      { fontname: 'rocket' },
      { fontname: 'shopping' },
      { fontname: 'folder' },
      { fontname: 'folder-open' },
      { fontname: 'folder-add' },
      { fontname: 'deploymentunit' },
      { fontname: 'accountbook' },
      { fontname: 'contacts' },
      { fontname: 'carryout' },
      { fontname: 'calendar-check' },
      { fontname: 'calendar' },
      { fontname: 'scan' },
      { fontname: 'select' },
      { fontname: 'boxplot' },
      { fontname: 'build' },
      { fontname: 'sliders' },
      { fontname: 'laptop' },
      { fontname: 'barcode' },
      { fontname: 'camera' },
      { fontname: 'cluster' },
      { fontname: 'gateway' },
      { fontname: 'car' },
      { fontname: 'printer' },
      { fontname: 'read' },
      { fontname: 'cloud-server' },
      { fontname: 'cloud-upload' },
      { fontname: 'cloud' },
      { fontname: 'cloud-download' },
      { fontname: 'cloud-sync' },
      { fontname: 'video' },
      { fontname: 'notification' },
      { fontname: 'sound' },
      { fontname: 'radarchart' },
      { fontname: 'qrcode' },
      { fontname: 'fund' },
      { fontname: 'image' },
      { fontname: 'mail' },
      { fontname: 'table' },
      { fontname: 'idcard' },
      { fontname: 'creditcard' },
      { fontname: 'heart' },
      { fontname: 'block' },
      { fontname: 'error' },
      { fontname: 'star' },
      { fontname: 'gold' },
      { fontname: 'heatmap' },
      { fontname: 'wifi' },
      { fontname: 'attachment' },
      { fontname: 'edit' },
      { fontname: 'key' },
      { fontname: 'api' },
      { fontname: 'disconnect' },
      { fontname: 'highlight' },
      { fontname: 'monitor' },
      { fontname: 'link' },
      { fontname: 'man' },
      { fontname: 'percentage' },
      { fontname: 'pushpin' },
      { fontname: 'phone' },
      { fontname: 'shake' },
      { fontname: 'tag' },
      { fontname: 'wrench' },
      { fontname: 'tags' },
      { fontname: 'scissor' },
      { fontname: 'mr' },
      { fontname: 'share' },
      { fontname: 'branches' },
      { fontname: 'fork' },
      { fontname: 'shrink' },
      { fontname: 'arrawsalt' },
      { fontname: 'verticalright' },
      { fontname: 'verticalleft' },
      { fontname: 'right' },
      { fontname: 'left' },
      { fontname: 'up' },
      { fontname: 'down' },
      { fontname: 'fullscreen' },
      { fontname: 'fullscreen-exit' },
      { fontname: 'doubleleft' },
      { fontname: 'doubleright' },
      { fontname: 'arrowright' },
      { fontname: 'arrowup' },
      { fontname: 'arrowleft' },
      { fontname: 'arrowdown' },
      { fontname: 'upload' },
      { fontname: 'colum-height' },
      { fontname: 'vertical-align-botto' },
      { fontname: 'vertical-align-middl' },
      { fontname: 'totop' },
      { fontname: 'vertical-align-top' },
      { fontname: 'download' },
      { fontname: 'sort-descending' },
      { fontname: 'sort-ascending' },
      { fontname: 'fall' },
      { fontname: 'swap' },
      { fontname: 'stock' },
      { fontname: 'rise' },
      { fontname: 'indent' },
      { fontname: 'outdent' },
      { fontname: 'menu' },
      { fontname: 'unorderedlist' },
      { fontname: 'orderedlist' },
      { fontname: 'align-right' },
      { fontname: 'align-center' },
      { fontname: 'align-left' },
      { fontname: 'pic-center' },
      { fontname: 'pic-right' },
      { fontname: 'pic-left' },
      { fontname: 'bold' },
      { fontname: 'font-colors' },
      { fontname: 'exclaimination' },
      { fontname: 'font-size' },
      { fontname: 'infomation' },
      { fontname: 'line-height' },
      { fontname: 'strikethrough' },
      { fontname: 'underline' },
      { fontname: 'number' },
      { fontname: 'italic' },
      { fontname: 'code' },
      { fontname: 'column-width' },
      { fontname: 'check' },
      { fontname: 'ellipsis' },
      { fontname: 'dash' },
      { fontname: 'close' },
      { fontname: 'enter' },
      { fontname: 'line' },
      { fontname: 'minus' },
      { fontname: 'question' },
      { fontname: 'plus' },
      { fontname: 'rollback' },
      { fontname: 'small-dash' },
      { fontname: 'pause' },
      { fontname: 'bg-colors' },
      { fontname: 'crown' },
      { fontname: 'drag' },
      { fontname: 'desktop' },
      { fontname: 'gift' },
      { fontname: 'stop' },
      { fontname: 'fire' },
      { fontname: 'thunderbolt' },
      { fontname: 'check-circle-fill' },
      { fontname: 'left-circle-fill' },
      { fontname: 'down-circle-fill' },
      { fontname: 'minus-circle-fill' },
      { fontname: 'close-circle-fill' },
      { fontname: 'info-circle-fill' },
      { fontname: 'up-circle-fill' },
      { fontname: 'right-circle-fill' },
      { fontname: 'plus-circle-fill' },
      { fontname: 'question-circle-fill' },
      { fontname: 'EURO-circle-fill' },
      { fontname: 'frown-fill' },
      { fontname: 'copyright-circle-fil' },
      { fontname: 'CI-circle-fill' },
      { fontname: 'compass-fill' },
      { fontname: 'Dollar-circle-fill' },
      { fontname: 'poweroff-circle-fill' },
      { fontname: 'meh-fill' },
      { fontname: 'play-circle-fill' },
      { fontname: 'Pound-circle-fill' },
      { fontname: 'smile-fill' },
      { fontname: 'stop-fill' },
      { fontname: 'warning-circle-fill' },
      { fontname: 'time-circle-fill' },
      { fontname: 'trademark-circle-fil' },
      { fontname: 'YUAN-circle-fill' },
      { fontname: 'heart-fill' },
      { fontname: 'piechart-circle-fil' },
      { fontname: 'dashboard-fill' },
      { fontname: 'message-fill' },
      { fontname: 'check-square-fill' },
      { fontname: 'down-square-fill' },
      { fontname: 'minus-square-fill' },
      { fontname: 'close-square-fill' },
      { fontname: 'codelibrary-fill' },
      { fontname: 'left-square-fill' },
      { fontname: 'play-square-fill' },
      { fontname: 'up-square-fill' },
      { fontname: 'right-square-fill' },
      { fontname: 'plus-square-fill' },
      { fontname: 'accountbook-fill' },
      { fontname: 'carryout-fill' },
      { fontname: 'calendar-fill' },
      { fontname: 'calculator-fill' },
      { fontname: 'interation-fill' },
      { fontname: 'project-fill' },
      { fontname: 'detail-fill' },
      { fontname: 'save-fill' },
      { fontname: 'wallet-fill' },
      { fontname: 'control-fill' },
      { fontname: 'layout-fill' },
      { fontname: 'appstore-fill' },
      { fontname: 'mobile-fill' },
      { fontname: 'tablet-fill' },
      { fontname: 'book-fill' },
      { fontname: 'redenvelope-fill' },
      { fontname: 'safetycertificate-f' },
      { fontname: 'propertysafety-fill' },
      { fontname: 'insurance-fill' },
      { fontname: 'securityscan-fill' },
      { fontname: 'file-exclamation-fil' },
      { fontname: 'file-add-fill' },
      { fontname: 'file-fill' },
      { fontname: 'file-excel-fill' },
      { fontname: 'file-markdown-fill' },
      { fontname: 'file-text-fill' },
      { fontname: 'file-ppt-fill' },
      { fontname: 'file-unknown-fill' },
      { fontname: 'file-word-fill' },
      { fontname: 'file-zip-fill' },
      { fontname: 'file-pdf-fill' },
      { fontname: 'file-image-fill' },
      { fontname: 'diff-fill' },
      { fontname: 'file-copy-fill' },
      { fontname: 'snippets-fill' },
      { fontname: 'batchfolding-fill' },
      { fontname: 'reconciliation-fill' },
      { fontname: 'folder-add-fill' },
      { fontname: 'folder-fill' },
      { fontname: 'folder-open-fill' },
      { fontname: 'database-fill' },
      { fontname: 'container-fill' },
      { fontname: 'sever-fill' },
      { fontname: 'calendar-check-fill' },
      { fontname: 'image-fill' },
      { fontname: 'idcard-fill' },
      { fontname: 'creditcard-fill' },
      { fontname: 'fund-fill' },
      { fontname: 'read-fill' },
      { fontname: 'contacts-fill' },
      { fontname: 'delete-fill' },
      { fontname: 'notification-fill' },
      { fontname: 'flag-fill' },
      { fontname: 'moneycollect-fill' },
      { fontname: 'medicinebox-fill' },
      { fontname: 'rest-fill' },
      { fontname: 'shopping-fill' },
      { fontname: 'skin-fill' },
      { fontname: 'video-fill' },
      { fontname: 'sound-fill' },
      { fontname: 'bulb-fill' },
      { fontname: 'bell-fill' },
      { fontname: 'filter-fill' },
      { fontname: 'fire-fill' },
      { fontname: 'funnelplot-fill' },
      { fontname: 'gift-fill' },
      { fontname: 'hourglass-fill' },
      { fontname: 'home-fill' },
      { fontname: 'trophy-fill' },
      { fontname: 'location-fill' },
      { fontname: 'cloud-fill' },
      { fontname: 'customerservice-fill' },
      { fontname: 'experiment-fill' },
      { fontname: 'eye-fill' },
      { fontname: 'like-fill' },
      { fontname: 'lock-fill' },
      { fontname: 'unlike-fill' },
      { fontname: 'star-fill' },
      { fontname: 'unlock-fill' },
      { fontname: 'alert-fill' },
      { fontname: 'api-fill' },
      { fontname: 'highlight-fill' },
      { fontname: 'phone-fill' },
      { fontname: 'edit-fill' },
      { fontname: 'pushpin-fill' },
      { fontname: 'rocket-fill' },
      { fontname: 'thunderbolt-fill' },
      { fontname: 'tag-fill' },
      { fontname: 'wrench-fill' },
      { fontname: 'tags-fill' },
      { fontname: 'bank-fill' },
      { fontname: 'camera-fill' },
      { fontname: 'error-fill' },
      { fontname: 'crown-fill' },
      { fontname: 'mail-fill' },
      { fontname: 'car-fill' },
      { fontname: 'printer-fill' },
      { fontname: 'shop-fill' },
      { fontname: 'setting-fill' },
      { fontname: 'USB-fill' },
      { fontname: 'golden-fill' },
      { fontname: 'build-fill' },
      { fontname: 'boxplot-fill' },
      { fontname: 'sliders-fill' },
      { fontname: 'alibaba' },
      { fontname: 'alibabacloud' },
      { fontname: 'antdesign' },
      { fontname: 'ant-cloud' },
      { fontname: 'behance' },
      { fontname: 'googleplus' },
      { fontname: 'medium' },
      { fontname: 'google' },
      { fontname: 'IE' },
      { fontname: 'amazon' },
      { fontname: 'slack' },
      { fontname: 'alipay' },
      { fontname: 'taobao' },
      { fontname: 'zhihu' },
      { fontname: 'HTML' },
      { fontname: 'linkedin' },
      { fontname: 'yahoo' },
      { fontname: 'facebook' },
      { fontname: 'skype' },
      { fontname: 'CodeSandbox' },
      { fontname: 'chrome' },
      { fontname: 'codepen' },
      { fontname: 'aliwangwang' },
      { fontname: 'apple' },
      { fontname: 'android' },
      { fontname: 'sketch' },
      { fontname: 'Gitlab' },
      { fontname: 'dribbble' },
      { fontname: 'instagram' },
      { fontname: 'reddit' },
      { fontname: 'windows' },
      { fontname: 'yuque' },
      { fontname: 'Youtube' },
      { fontname: 'Gitlab-fill' },
      { fontname: 'dropbox' },
      { fontname: 'dingtalk' },
      { fontname: 'android-fill' },
      { fontname: 'apple-fill' },
      { fontname: 'HTML-fill' },
      { fontname: 'windows-fill' },
      { fontname: 'QQ' },
      { fontname: 'twitter' },
      { fontname: 'skype-fill' },
      { fontname: 'weibo' },
      { fontname: 'yuque-fill' },
      { fontname: 'Youtube-fill' },
      { fontname: 'yahoo-fill' },
      { fontname: 'wechat-fill' },
      { fontname: 'chrome-fill' },
      { fontname: 'alipay-circle-fill' },
      { fontname: 'aliwangwang-fill' },
      { fontname: 'behance-circle-fill' },
      { fontname: 'amazon-circle-fill' },
      { fontname: 'codepen-circle-fill' },
      { fontname: 'CodeSandbox-circle-f' },
      { fontname: 'dropbox-circle-fill' },
      { fontname: 'github-fill' },
      { fontname: 'dribbble-circle-fill' },
      { fontname: 'googleplus-circle-f' },
      { fontname: 'medium-circle-fill' },
      { fontname: 'QQ-circle-fill' },
      { fontname: 'IE-circle-fill' },
      { fontname: 'google-circle-fill' },
      { fontname: 'dingtalk-circle-fill' },
      { fontname: 'sketch-circle-fill' },
      { fontname: 'slack-circle-fill' },
      { fontname: 'twitter-circle-fill' },
      { fontname: 'taobao-circle-fill' },
      { fontname: 'weibo-circle-fill' },
      { fontname: 'zhihu-circle-fill' },
      { fontname: 'reddit-circle-fill' },
      { fontname: 'alipay-square-fill' },
      { fontname: 'dingtalk-square-fill' },
      { fontname: 'CodeSandbox-square-f' },
      { fontname: 'behance-square-fill' },
      { fontname: 'amazon-square-fill' },
      { fontname: 'codepen-square-fill' },
      { fontname: 'dribbble-square-fill' },
      { fontname: 'dropbox-square-fill' },
      { fontname: 'facebook-fill' },
      { fontname: 'googleplus-square-f' },
      { fontname: 'google-square-fill' },
      { fontname: 'instagram-fill' },
      { fontname: 'IE-square-fill' },
      { fontname: 'medium-square-fill' },
      { fontname: 'linkedin-fill' },
      { fontname: 'QQ-square-fill' },
      { fontname: 'reddit-square-fill' },
      { fontname: 'twitter-square-fill' },
      { fontname: 'sketch-square-fill' },
      { fontname: 'slack-square-fill' },
      { fontname: 'taobao-square-fill' },
      { fontname: 'weibo-square-fill' },
      { fontname: 'zhihu-square-fill' },
      { fontname: 'zoomout' },
      { fontname: 'apartment' },
      { fontname: 'audio' },
      { fontname: 'audio-fill' },
      { fontname: 'robot' },
      { fontname: 'zoomin' },
      { fontname: 'robot-fill' },
      { fontname: 'bug-fill' },
      { fontname: 'bug' },
      { fontname: 'audiostatic' },
      { fontname: 'comment' },
      { fontname: 'signal-fill' },
      { fontname: 'verified' },
      { fontname: 'shortcut-fill' },
      { fontname: 'videocameraadd' },
      { fontname: 'switchuser' },
      { fontname: 'whatsapp' },
      { fontname: 'appstoreadd' },
      { fontname: 'caret-down' },
      { fontname: 'backward' },
      { fontname: 'caret-up' },
      { fontname: 'caret-right' },
      { fontname: 'caret-left' },
      { fontname: 'fast-backward' },
      { fontname: 'forward' },
      { fontname: 'fast-forward' },
      { fontname: 'search' },
      { fontname: 'retweet' },
      { fontname: 'login' },
      { fontname: 'step-backward' },
      { fontname: 'step-forward' },
      { fontname: 'swap-right' },
      { fontname: 'swap-left' },
      { fontname: 'woman' },
    ]
  },

  copyfont: function (e) {
    console.log(e)
    wx.setClipboardData({
      data: e.currentTarget.dataset.text,
      success: function (res) {
        wx.getClipboardData({
          success: function (res) {
            wx.showToast({
              title: '复制成功'
            })
          }
        })
      }
    })
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})