// pages/icon/ion-ios.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    fontclass: [

      { fontname: 'ios-add' },
      { fontname: 'ios-add-circle' },
      { fontname: 'ios-add-circle-outli' },
      { fontname: 'ios-albums' },
      { fontname: 'ios-alert' },
      { fontname: 'ios-airplane' },
      { fontname: 'ios-analytics' },
      { fontname: 'ios-arrow-down' },
      { fontname: 'ios-appstore' },
      { fontname: 'ios-alarm' },
      { fontname: 'ios-arrow-dropdown-c' },
      { fontname: 'ios-apps' },
      { fontname: 'ios-american-footbal' },
      { fontname: 'ios-archive' },
      { fontname: 'ios-arrow-dropup-cir' },
      { fontname: 'ios-arrow-dropright' },
      { fontname: 'ios-arrow-dropleft-c' },
      { fontname: 'ios-arrow-round-forw' },
      { fontname: 'ios-arrow-dropright-' },
      { fontname: 'ios-arrow-forward' },
      { fontname: 'ios-arrow-dropdown' },
      { fontname: 'ios-arrow-up' },
      { fontname: 'ios-arrow-round-back' },
      { fontname: 'ios-arrow-round-up' },
      { fontname: 'ios-arrow-back' },
      { fontname: 'ios-backspace' },
      { fontname: 'ios-aperture' },
      { fontname: 'ios-at' },
      { fontname: 'ios-arrow-dropup' },
      { fontname: 'ios-barcode' },
      { fontname: 'ios-battery-full' },
      { fontname: 'ios-battery-charging' },
      { fontname: 'ios-arrow-round-down' },
      { fontname: 'ios-battery-dead' },
      { fontname: 'ios-basketball' },
      { fontname: 'ios-basket' },
      { fontname: 'ios-bed' },
      { fontname: 'ios-bicycle' },
      { fontname: 'ios-book' },
      { fontname: 'ios-boat' },
      { fontname: 'ios-beer' },
      { fontname: 'ios-bluetooth' },
      { fontname: 'ios-browsers' },
      { fontname: 'ios-body' },
      { fontname: 'ios-bonfire' },
      { fontname: 'ios-bookmarks' },
      { fontname: 'ios-brush' },
      { fontname: 'ios-bulb' },
      { fontname: 'ios-cafe' },
      { fontname: 'ios-bowtie' },
      { fontname: 'ios-bookmark' },
      { fontname: 'ios-car' },
      { fontname: 'ios-card' },
      { fontname: 'ios-attach' },
      { fontname: 'ios-arrow-dropleft' },
      { fontname: 'ios-cash' },
      { fontname: 'ios-call' },
      { fontname: 'ios-checkbox-outline' },
      { fontname: 'ios-cellular' },
      { fontname: 'ios-briefcase' },
      { fontname: 'ios-build' },
      { fontname: 'ios-baseball' },
      { fontname: 'ios-checkmark-circle' },
      { fontname: 'ios-calendar' },
      { fontname: 'ios-chatboxes' },
      { fontname: 'ios-cloud-download' },
      { fontname: 'ios-cloud-done' },
      { fontname: 'ios-close' },
      { fontname: 'ios-close-circle' },
      { fontname: 'ios-cloudy' },
      { fontname: 'ios-clipboard' },
      { fontname: 'ios-close-circle-out' },
      { fontname: 'ios-clock' },
      { fontname: 'ios-code-download' },
      { fontname: 'ios-code' },
      { fontname: 'ios-beaker' },
      { fontname: 'ios-cloud-upload' },
      { fontname: 'ios-bug' },
      { fontname: 'ios-color-filter' },
      { fontname: 'ios-crop' },
      { fontname: 'ios-color-palette' },
      { fontname: 'ios-contacts' },
      { fontname: 'ios-copy' },
      { fontname: 'ios-compass' },
      { fontname: 'ios-contract' },
      { fontname: 'ios-cog' },
      { fontname: 'ios-calculator' },
      { fontname: 'ios-bus' },
      { fontname: 'ios-download' },
      { fontname: 'ios-done-all' },
      { fontname: 'ios-document' },
      { fontname: 'ios-cloud-outline' },
      { fontname: 'ios-cloudy-night' },
      { fontname: 'ios-cloud' },
      { fontname: 'ios-create' },
      { fontname: 'ios-cube' },
      { fontname: 'ios-color-fill' },
      { fontname: 'ios-desktop' },
      { fontname: 'ios-fastforward' },
      { fontname: 'ios-flash' },
      { fontname: 'ios-disc' },
      { fontname: 'ios-female' },
      { fontname: 'ios-business' },
      { fontname: 'ios-easel' },
      { fontname: 'ios-exit' },
      { fontname: 'ios-film' },
      { fontname: 'ios-filing' },
      { fontname: 'ios-flask' },
      { fontname: 'ios-egg' },
      { fontname: 'ios-flashlight' },
      { fontname: 'ios-expand' },
      { fontname: 'ios-camera' },
      { fontname: 'ios-checkmark-circle1' },
      { fontname: 'ios-chatbubbles' },
      { fontname: 'ios-folder-open' },
      { fontname: 'ios-funnel' },
      { fontname: 'ios-construct' },
      { fontname: 'ios-git-network' },
      { fontname: 'ios-flash-off' },
      { fontname: 'ios-fitness' },
      { fontname: 'ios-git-compare' },
      { fontname: 'ios-git-pull-request' },
      { fontname: 'ios-flame' },
      { fontname: 'ios-git-commit' },
      { fontname: 'ios-checkmark' },
      { fontname: 'ios-cart' },
      { fontname: 'ios-eye' },
      { fontname: 'ios-headset' },
      { fontname: 'ios-happy' },
      { fontname: 'ios-cut' },
      { fontname: 'ios-hand' },
      { fontname: 'ios-flower' },
      { fontname: 'ios-infinite' },
      { fontname: 'ios-heart-dislike' },
      { fontname: 'ios-code-working' },
      { fontname: 'ios-cloud-circle' },
      { fontname: 'ios-checkbox' },
      { fontname: 'ios-contact' },
      { fontname: 'ios-folder' },
      { fontname: 'ios-gift' },
      { fontname: 'ios-heart-empty' },
      { fontname: 'ios-football' },
      { fontname: 'ios-flag' },
      { fontname: 'ios-hammer' },
      { fontname: 'ios-heart' },
      { fontname: 'ios-key' },
      { fontname: 'ios-home' },
      { fontname: 'ios-help' },
      { fontname: 'ios-information' },
      { fontname: 'ios-globe' },
      { fontname: 'ios-leaf' },
      { fontname: 'ios-image' },
      { fontname: 'ios-grid' },
      { fontname: 'ios-git-merge' },
      { fontname: 'ios-log-in' },
      { fontname: 'ios-color-wand' },
      { fontname: 'ios-list' },
      { fontname: 'ios-mail-open' },
      { fontname: 'ios-images' },
      { fontname: 'ios-laptop' },
      { fontname: 'ios-keypad' },
      { fontname: 'ios-eye-off' },
      { fontname: 'ios-help-circle-outl' },
      { fontname: 'ios-jet' },
      { fontname: 'ios-contrast' },
      { fontname: 'ios-information-circ' },
      { fontname: 'ios-locate' },
      { fontname: 'ios-magnet' },
      { fontname: 'ios-journal' },
      { fontname: 'ios-help-circle' },
      { fontname: 'ios-heart-half' },
      { fontname: 'ios-medkit' },
      { fontname: 'ios-ice-cream' },
      { fontname: 'ios-log-out' },
      { fontname: 'ios-medal' },
      { fontname: 'ios-hourglass' },
      { fontname: 'ios-mail-unread' },
      { fontname: 'ios-git-branch' },
      { fontname: 'ios-information-circ1' },
      { fontname: 'ios-glasses' },
      { fontname: 'ios-list-box' },
      { fontname: 'ios-link' },
      { fontname: 'ios-microphone' },
      { fontname: 'ios-menu' },
      { fontname: 'ios-map' },
      { fontname: 'ios-help-buoy' },
      { fontname: 'ios-male' },
      { fontname: 'ios-finger-print' },
      { fontname: 'ios-man' },
      { fontname: 'ios-navigate' },
      { fontname: 'ios-move' },
      { fontname: 'ios-medical' },
      { fontname: 'ios-lock' },
      { fontname: 'ios-musical-notes' },
      { fontname: 'ios-notifications-of' },
      { fontname: 'ios-notifications' },
      { fontname: 'ios-open' },
      { fontname: 'ios-nutrition' },
      { fontname: 'ios-paper-plane' },
      { fontname: 'ios-mail' },
      { fontname: 'ios-pause' },
      { fontname: 'ios-options' },
      { fontname: 'ios-mic-off' },
      { fontname: 'ios-paper' },
      { fontname: 'ios-person-add' },
      { fontname: 'ios-musical-note' },
      { fontname: 'ios-nuclear' },
      { fontname: 'ios-pin' },
      { fontname: 'ios-moon' },
      { fontname: 'ios-phone-portrait' },
      { fontname: 'ios-people' },
      { fontname: 'ios-photos' },
      { fontname: 'ios-planet' },
      { fontname: 'ios-podium' },
      { fontname: 'ios-partly-sunny' },
      { fontname: 'ios-play-circle' },
      { fontname: 'ios-mic' },
      { fontname: 'ios-power' },
      { fontname: 'ios-pricetags' },
      { fontname: 'ios-phone-landscape' },
      { fontname: 'ios-print' },
      { fontname: 'ios-radio-button-on' },
      { fontname: 'ios-notifications-ou' },
      { fontname: 'ios-person' },
      { fontname: 'ios-qr-scanner' },
      { fontname: 'ios-recording' },
      { fontname: 'ios-pie' },
      { fontname: 'ios-megaphone' },
      { fontname: 'ios-quote' },
      { fontname: 'ios-outlet' },
      { fontname: 'ios-pint' },
      { fontname: 'ios-pricetag' },
      { fontname: 'ios-pulse' },
      { fontname: 'ios-refresh' },
      { fontname: 'ios-redo' },
      { fontname: 'ios-remove' },
      { fontname: 'ios-reorder' },
      { fontname: 'ios-radio-button-off' },
      { fontname: 'ios-paw' },
      { fontname: 'ios-radio' },
      { fontname: 'ios-return-right' },
      { fontname: 'ios-rainy' },
      { fontname: 'ios-remove-circle' },
      { fontname: 'ios-return-left' },
      { fontname: 'ios-ribbon' },
      { fontname: 'ios-remove-circle-ou' },
      { fontname: 'ios-rocket' },
      { fontname: 'ios-reverse-camera' },
      { fontname: 'ios-sad' },
      { fontname: 'ios-restaurant' },
      { fontname: 'ios-play' },
      { fontname: 'ios-more' },
      { fontname: 'ios-pizza' },
      { fontname: 'ios-repeat' },
      { fontname: 'ios-search' },
      { fontname: 'ios-share-alt' },
      { fontname: 'ios-share' },
      { fontname: 'ios-skip-backward' },
      { fontname: 'ios-send' },
      { fontname: 'ios-rose' },
      { fontname: 'ios-save' },
      { fontname: 'ios-square' },
      { fontname: 'ios-rewind' },
      { fontname: 'ios-star-half' },
      { fontname: 'ios-school' },
      { fontname: 'ios-refresh-circle' },
      { fontname: 'ios-skip-forward' },
      { fontname: 'ios-snow' },
      { fontname: 'ios-settings' },
      { fontname: 'ios-speedometer' },
      { fontname: 'ios-stats' },
      { fontname: 'ios-shirt' },
      { fontname: 'ios-square-outline' },
      { fontname: 'ios-subway' },
      { fontname: 'ios-sunny' },
      { fontname: 'ios-switch' },
      { fontname: 'ios-sync' },
      { fontname: 'ios-tennisball' },
      { fontname: 'ios-stopwatch' },
      { fontname: 'ios-tablet-landscape' },
      { fontname: 'ios-thermometer' },
      { fontname: 'ios-swap' },
      { fontname: 'ios-tablet-portrait' },
      { fontname: 'ios-thumbs-down' },
      { fontname: 'ios-time' },
      { fontname: 'ios-today' },
      { fontname: 'ios-star-outline' },
      { fontname: 'ios-shuffle' },
      { fontname: 'ios-thunderstorm' },
      { fontname: 'ios-thumbs-up' },
      { fontname: 'ios-train' },
      { fontname: 'ios-timer' },
      { fontname: 'ios-text' },
      { fontname: 'ios-resize' },
      { fontname: 'ios-trending-down' },
      { fontname: 'ios-star' },
      { fontname: 'ios-trophy' },
      { fontname: 'ios-tv' },
      { fontname: 'ios-trash' },
      { fontname: 'ios-trending-up' },
      { fontname: 'ios-unlock' },
      { fontname: 'ios-volume-mute' },
      { fontname: 'ios-transgender' },
      { fontname: 'ios-undo' },
      { fontname: 'ios-umbrella' },
      { fontname: 'ios-volume-low' },
      { fontname: 'ios-wallet' },
      { fontname: 'ios-warning' },
      { fontname: 'ios-videocam' },
      { fontname: 'ios-water' },
      { fontname: 'ios-volume-off' },
      { fontname: 'ios-volume-high' },
      { fontname: 'ios-walk' },
      { fontname: 'ios-wifi' },
      { fontname: 'ios-woman' },
      { fontname: 'ios-watch' },
      { fontname: 'ios-wine' },
      { fontname: 'logo-angular' },
      { fontname: 'logo-bitbucket' },
      { fontname: 'logo-apple' },
      { fontname: 'logo-android' },
      { fontname: 'logo-bitcoin' },
      { fontname: 'logo-designernews' },
      { fontname: 'logo-css' },
      { fontname: 'logo-dropbox' },
      { fontname: 'logo-flickr' },
      { fontname: 'logo-dribbble' },
      { fontname: 'logo-closed-captioni' },
      { fontname: 'logo-game-controller' },
      { fontname: 'logo-euro' },
      { fontname: 'logo-html' },
      { fontname: 'logo-codepen' },
      { fontname: 'logo-hackernews' },
      { fontname: 'logo-github' },
      { fontname: 'logo-game-controller1' },
      { fontname: 'logo-freebsd-devil' },
      { fontname: 'logo-googleplus' },
      { fontname: 'logo-google' },
      { fontname: 'logo-instagram' },
      { fontname: 'logo-facebook' },
      { fontname: 'logo-foursquare' },
      { fontname: 'logo-buffer' },
      { fontname: 'logo-javascript' },
      { fontname: 'logo-ionitron' },
      { fontname: 'logo-linkedin' },
      { fontname: 'logo-ionic' },
      { fontname: 'logo-rss' },
      { fontname: 'logo-polymer' },
      { fontname: 'logo-octocat' },
      { fontname: 'logo-markdown' },
      { fontname: 'logo-pinterest' },
      { fontname: 'logo-model-s' },
      { fontname: 'logo-slack' },
      { fontname: 'logo-chrome' },
      { fontname: 'logo-npm' },
      { fontname: 'logo-tumblr' },
      { fontname: 'logo-steam' },
      { fontname: 'logo-reddit' },
      { fontname: 'logo-twitter' },
      { fontname: 'logo-nodejs' },
      { fontname: 'logo-no-smoking' },
      { fontname: 'logo-skype' },
      { fontname: 'logo-yahoo' },
      { fontname: 'logo-vimeo' },
      { fontname: 'logo-twitch' },
      { fontname: 'logo-vk' },
      { fontname: 'logo-playstation' },
      { fontname: 'logo-tux' },
      { fontname: 'logo-xing' },
      { fontname: 'logo-youtube' },
      { fontname: 'logo-windows' },
      { fontname: 'logo-python' },
      { fontname: 'logo-wordpress' },
      { fontname: 'logo-yen' },
      { fontname: 'logo-sass' },
      { fontname: 'logo-snapchat' },
      { fontname: 'logo-usd' },
      { fontname: 'logo-xbox' },
      { fontname: 'logo-whatsapp' }
    ]
  },

  copyfont: function (e) {
    console.log(e)
    wx.setClipboardData({
      data: e.currentTarget.dataset.text,
      success: function (res) {
        wx.getClipboardData({
          success: function (res) {
            wx.showToast({
              title: '复制成功'
            })
          }
        })
      }
    })
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})