// pages/icon/ion-android.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    fontclass: [
      { fontname: 'md-add' },
      { fontname: 'md-add-circle-outlin' },
      { fontname: 'md-add-circle' },
      { fontname: 'md-american-football' },
      { fontname: 'md-alert' },
      { fontname: 'md-analytics' },
      { fontname: 'md-airplane' },
      { fontname: 'md-alarm' },
      { fontname: 'md-archive' },
      { fontname: 'md-apps' },
      { fontname: 'md-albums' },
      { fontname: 'md-arrow-down' },
      { fontname: 'md-arrow-back' },
      { fontname: 'md-appstore' },
      { fontname: 'md-arrow-dropdown-ci' },
      { fontname: 'md-arrow-dropdown' },
      { fontname: 'md-arrow-dropright' },
      { fontname: 'md-arrow-round-back' },
      { fontname: 'md-arrow-dropleft-ci' },
      { fontname: 'md-arrow-dropup' },
      { fontname: 'md-arrow-round-forwa' },
      { fontname: 'md-arrow-round-down' },
      { fontname: 'md-aperture' },
      { fontname: 'md-arrow-round-up' },
      { fontname: 'md-arrow-up' },
      { fontname: 'md-arrow-forward' },
      { fontname: 'md-barcode' },
      { fontname: 'md-battery-charging' },
      { fontname: 'md-arrow-dropup-circ' },
      { fontname: 'md-basket' },
      { fontname: 'md-battery-full' },
      { fontname: 'md-basketball' },
      { fontname: 'md-battery-dead' },
      { fontname: 'md-at' },
      { fontname: 'md-baseball' },
      { fontname: 'md-bluetooth' },
      { fontname: 'md-arrow-dropleft' },
      { fontname: 'md-bed' },
      { fontname: 'md-body' },
      { fontname: 'md-arrow-dropright-c' },
      { fontname: 'md-book' },
      { fontname: 'md-briefcase' },
      { fontname: 'md-browsers' },
      { fontname: 'md-beaker' },
      { fontname: 'md-bicycle' },
      { fontname: 'md-bowtie' },
      { fontname: 'md-bookmarks' },
      { fontname: 'md-bonfire' },
      { fontname: 'md-beer' },
      { fontname: 'md-build' },
      { fontname: 'md-cafe' },
      { fontname: 'md-backspace' },
      { fontname: 'md-business' },
      { fontname: 'md-calculator' },
      { fontname: 'md-boat' },
      { fontname: 'md-camera' },
      { fontname: 'md-calendar' },
      { fontname: 'md-bug' },
      { fontname: 'md-call' },
      { fontname: 'md-cellular' },
      { fontname: 'md-brush' },
      { fontname: 'md-cash' },
      { fontname: 'md-bulb' },
      { fontname: 'md-car' },
      { fontname: 'md-checkmark-circle-' },
      { fontname: 'md-card' },
      { fontname: 'md-chatbubbles' },
      { fontname: 'md-checkbox' },
      { fontname: 'md-close-circle-outl' },
      { fontname: 'md-checkbox-outline' },
      { fontname: 'md-close' },
      { fontname: 'md-clipboard' },
      { fontname: 'md-cloud-done' },
      { fontname: 'md-checkmark-circle' },
      { fontname: 'md-clock' },
      { fontname: 'md-cloud-download' },
      { fontname: 'md-close-circle' },
      { fontname: 'md-chatboxes' },
      { fontname: 'md-cloud-upload' },
      { fontname: 'md-checkmark' },
      { fontname: 'md-cloud' },
      { fontname: 'md-cloudy-night' },
      { fontname: 'md-code-download' },
      { fontname: 'md-cloud-outline' },
      { fontname: 'md-attach' },
      { fontname: 'md-cloudy' },
      { fontname: 'md-cloud-circle' },
      { fontname: 'md-code' },
      { fontname: 'md-cog' },
      { fontname: 'md-code-working' },
      { fontname: 'md-compass' },
      { fontname: 'md-color-filter' },
      { fontname: 'md-bus' },
      { fontname: 'md-color-wand' },
      { fontname: 'md-color-palette' },
      { fontname: 'md-construct' },
      { fontname: 'md-contact' },
      { fontname: 'md-copy' },
      { fontname: 'md-create' },
      { fontname: 'md-contrast' },
      { fontname: 'md-cut' },
      { fontname: 'md-desktop' },
      { fontname: 'md-contacts' },
      { fontname: 'md-document' },
      { fontname: 'md-color-fill' },
      { fontname: 'md-done-all' },
      { fontname: 'md-disc' },
      { fontname: 'md-cube' },
      { fontname: 'md-easel' },
      { fontname: 'md-crop' },
      { fontname: 'md-eye-off' },
      { fontname: 'md-expand' },
      { fontname: 'md-download' },
      { fontname: 'md-female' },
      { fontname: 'md-film' },
      { fontname: 'md-fitness' },
      { fontname: 'md-exit' },
      { fontname: 'md-egg' },
      { fontname: 'md-bookmark' },
      { fontname: 'md-flag' },
      { fontname: 'md-eye' },
      { fontname: 'md-flame' },
      { fontname: 'md-flash' },
      { fontname: 'md-flash-off' },
      { fontname: 'md-flower' },
      { fontname: 'md-flask' },
      { fontname: 'md-folder' },
      { fontname: 'md-football' },
      { fontname: 'md-flashlight' },
      { fontname: 'md-finger-print' },
      { fontname: 'md-funnel' },
      { fontname: 'md-gift' },
      { fontname: 'md-git-branch' },
      { fontname: 'md-cart' },
      { fontname: 'md-git-compare' },
      { fontname: 'md-folder-open' },
      { fontname: 'md-git-network' },
      { fontname: 'md-git-commit' },
      { fontname: 'md-glasses' },
      { fontname: 'md-contract' },
      { fontname: 'md-git-pull-request' },
      { fontname: 'md-grid' },
      { fontname: 'md-heart-dislike' },
      { fontname: 'md-git-merge' },
      { fontname: 'md-headset' },
      { fontname: 'md-globe' },
      { fontname: 'md-fastforward' },
      { fontname: 'md-happy' },
      { fontname: 'md-hammer' },
      { fontname: 'md-help-buoy' },
      { fontname: 'md-heart' },
      { fontname: 'md-hand' },
      { fontname: 'md-heart-empty' },
      { fontname: 'md-help-circle' },
      { fontname: 'md-home' },
      { fontname: 'md-heart-half' },
      { fontname: 'md-ice-cream' },
      { fontname: 'md-image' },
      { fontname: 'md-help' },
      { fontname: 'md-hourglass' },
      { fontname: 'md-jet' },
      { fontname: 'md-images' },
      { fontname: 'md-information-circl' },
      { fontname: 'md-infinite' },
      { fontname: 'md-key' },
      { fontname: 'md-information-circl1' },
      { fontname: 'md-information' },
      { fontname: 'md-leaf' },
      { fontname: 'md-keypad' },
      { fontname: 'md-laptop' },
      { fontname: 'md-link' },
      { fontname: 'md-list' },
      { fontname: 'md-journal' },
      { fontname: 'md-locate' },
      { fontname: 'md-log-in' },
      { fontname: 'md-list-box' },
      { fontname: 'md-mail-open' },
      { fontname: 'md-magnet' },
      { fontname: 'md-lock' },
      { fontname: 'md-mail-unread' },
      { fontname: 'md-mail' },
      { fontname: 'md-log-out' },
      { fontname: 'md-medal' },
      { fontname: 'md-filing' },
      { fontname: 'md-male' },
      { fontname: 'md-map' },
      { fontname: 'md-man' },
      { fontname: 'md-medkit' },
      { fontname: 'md-medical' },
      { fontname: 'md-megaphone' },
      { fontname: 'md-mic-off' },
      { fontname: 'md-menu' },
      { fontname: 'md-mic' },
      { fontname: 'md-microphone' },
      { fontname: 'md-more' },
      { fontname: 'md-musical-notes' },
      { fontname: 'md-move' },
      { fontname: 'md-navigate' },
      { fontname: 'md-notifications' },
      { fontname: 'md-musical-note' },
      { fontname: 'md-nutrition' },
      { fontname: 'md-notifications-off' },
      { fontname: 'md-open' },
      { fontname: 'md-notifications-out' },
      { fontname: 'md-outlet' },
      { fontname: 'md-nuclear' },
      { fontname: 'md-paper-plane' },
      { fontname: 'md-options' },
      { fontname: 'md-partly-sunny' },
      { fontname: 'md-person-add' },
      { fontname: 'md-pause' },
      { fontname: 'md-paper' },
      { fontname: 'md-phone-portrait' },
      { fontname: 'md-people' },
      { fontname: 'md-help-circle-outli' },
      { fontname: 'md-moon' },
      { fontname: 'md-pie' },
      { fontname: 'md-person' },
      { fontname: 'md-paw' },
      { fontname: 'md-phone-landscape' },
      { fontname: 'md-pin' },
      { fontname: 'md-planet' },
      { fontname: 'md-pint' },
      { fontname: 'md-podium' },
      { fontname: 'md-play-circle' },
      { fontname: 'md-print' },
      { fontname: 'md-qr-scanner' },
      { fontname: 'md-pricetag' },
      { fontname: 'md-pizza' },
      { fontname: 'md-radio-button-on' },
      { fontname: 'md-quote' },
      { fontname: 'md-radio' },
      { fontname: 'md-pulse' },
      { fontname: 'md-play' },
      { fontname: 'md-photos' },
      { fontname: 'md-power' },
      { fontname: 'md-pricetags' },
      { fontname: 'logo-android' },
      { fontname: 'logo-angular' },
      { fontname: 'logo-apple' },
      { fontname: 'logo-css' },
      { fontname: 'logo-designernews' },
      { fontname: 'logo-bitbucket' },
      { fontname: 'logo-bitcoin' },
      { fontname: 'logo-dropbox' },
      { fontname: 'logo-facebook' },
      { fontname: 'logo-closed-captioni' },
      { fontname: 'logo-flickr' },
      { fontname: 'logo-googleplus' },
      { fontname: 'logo-dribbble' },
      { fontname: 'logo-euro' },
      { fontname: 'logo-buffer' },
      { fontname: 'logo-google' },
      { fontname: 'logo-html' },
      { fontname: 'logo-chrome' },
      { fontname: 'logo-ionic' },
      { fontname: 'logo-foursquare' },
      { fontname: 'logo-instagram' },
      { fontname: 'logo-markdown' },
      { fontname: 'logo-game-controller' },
      { fontname: 'logo-linkedin' },
      { fontname: 'logo-model-s' },
      { fontname: 'logo-freebsd-devil' },
      { fontname: 'logo-ionitron' },
      { fontname: 'logo-npm' },
      { fontname: 'logo-javascript' },
      { fontname: 'logo-no-smoking' },
      { fontname: 'logo-twitch' },
      { fontname: 'logo-polymer' },
      { fontname: 'logo-hackernews' },
      { fontname: 'logo-skype' },
      { fontname: 'logo-pinterest' },
      { fontname: 'logo-codepen' },
      { fontname: 'logo-game-controller1' },
      { fontname: 'logo-xing' },
      { fontname: 'logo-octocat' },
      { fontname: 'logo-playstation' },
      { fontname: 'logo-steam' },
      { fontname: 'logo-slack' },
      { fontname: 'logo-youtube' },
      { fontname: 'logo-vimeo' },
      { fontname: 'logo-tumblr' },
      { fontname: 'logo-vk' },
      { fontname: 'logo-nodejs' },
      { fontname: 'logo-rss' },
      { fontname: 'logo-python' },
      { fontname: 'logo-windows' },
      { fontname: 'logo-tux' },
      { fontname: 'logo-twitter' },
      { fontname: 'logo-yahoo' },
      { fontname: 'logo-github' },
      { fontname: 'logo-wordpress' },
      { fontname: 'logo-reddit' },
      { fontname: 'logo-yen' },
      { fontname: 'logo-sass' },
      { fontname: 'logo-xbox' },
      { fontname: 'logo-usd' },
      { fontname: 'logo-whatsapp' },
      { fontname: 'logo-snapchat' }
    ]
  },

  copyfont: function (e) {
    console.log(e)
    wx.setClipboardData({
      data: e.currentTarget.dataset.text,
      success: function (res) {
        wx.getClipboardData({
          success: function (res) {
            wx.showToast({
              title: '复制成功'
            })
          }
        })
      }
    })
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})